### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Members

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
@Harshothpabbati approve this.

**Comment by HarshKhandeparkar** [comment]
@Harshithpabbati I have made changes. You will have to approve again.

**Comment by HarshKhandeparkar** [comment]
Thanks. Shall I merge this? Will it affect your installation pr?

**Comment by Harshithpabbati** [comment]
Done!

**Comment by Harshithpabbati** [comment]
Merge it

**Comment by HarshKhandeparkar** [comment]
Done :tada:

**Pull request merged**
